# Github Actions CI/CD za Next.js aplikaciju
# Pokreće se na svaki push i pull request na main granu
name: Next.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout koda
        uses: actions/checkout@v4
      - name: Instalacija Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Instalacija pnpm
        run: npm install -g pnpm
      - name: Instalacija dependencija
        run: pnpm ci
      - name: Build projekta
        run: pnpm run build

      - name: Lint provera (ESLint)
        run: pnpm run lint

      # - name: Pokretanje unit testova (Jest)
      #   run: pnpm run test:unit

      # - name: Pokretanje integration testova (Jest)
      #   run: pnpm run test:integration

      # - name: Pokretanje E2E testova (Playwright)
      #   run: |
      #     pnpm exec playwright install --with-deps
      #     pnpm run test:e2e

      - name: Security audit (npm audit)
        run: pnpm run audit
